######################################################################
# Automatically generated by qmake (3.0) ?? 2? 8 23:39:32 2017
######################################################################
QT += widgets
QT += sql
TEMPLATE = app
TARGET = exam
INCLUDEPATH += .

# Input
HEADERS += mainpage.h setexamkemupage.h setexampage.h
SOURCES += main.cpp mainpage.cpp setexamkemupage.cpp setexampage.cpp
RESOURCES += exampage.qrc
